title: 5p-blog
description: > # this means to ignore newlines until "baseurl:"
  Pyeong oh의 개인 블로그 입니다. 개인적으로 공부하거나 알게된 것들을 정리합니다.
permalink: ":title/"
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Oh Pyeong # add your name
author-img: pyeong.jpeg # add your photo
about-author: I am a web developer focusing on front-end development. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: pyeongoh5 # add your Github handle
social-linkedin: pyeong-oh-699b52186 # add your Linkedin handle
social-email: pyeong.oh5@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
